server:
  port: 8081

spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

management:
  endpoint:
    loggers:
      enabled: true
  health:
    rabbit:
      enabled: false
  endpoints:
    web:
      exposure:
        include: "health, info, loggers"